### ISSUE TITLE
Explicit exhibit loading is incompatible with rails' autoreload

### ISSUE THREAD

**Issue by pdobb** [objects-on-rails/display-case#55]
I've been experiencing a problem with autoreloading of exhibits. Any time I update the code in an exhibit I have to restart my server to get the new code. I've done some digging and found that this is specific to the `explicit` configuration option. When I use, e.g.

    DisplayCase.configure do |config|
      config.explicit = true
      config.exhibits = [
        OneExhibit,
        TwoExhibit
      ]
    end

then autoreloading stops working. If I comment out the `config.explicit` option (which causes the `config.exhibits` option to be ignored) then autoreloading works. I've tried this in Rails 3.2 and 4.1. I've also tried this with Ruby 1.9.3 and Ruby 2.2. All environments are consistent in this behavior.

I have an example, base application here: https://github.com/pdobb/display_case_reexhibit_test_app-rails_3.2

To recreate the issue just clone the repo and:
1. `bundle install` (currently setup for Ruby 1.9.3... if using Ruby 2 change the `pry-debugger` gem to `pry-byebug` ... or just comment out.)
2. `rails s`
3. Visit: [http://localhost:3000](http://localhost:3000)
4. Reload
5. Open app/exhibits/one_exhibit.rb and add an invalid expression to the top of OneExhibit#do_render_with_self1
6. Reload

You will notice the exception does not trip until restarting the server and reloading the page. But, if you remove the explicit exhibit loading in config/initializers/display_case.rb and repeat the above autoreloading will work as expected.

I plan to try digging into the gem and see if I can figure out what's going on here... but may need help.

Thanks!

**Comment by codeodor** [comment]
Thanks for reporting it Paul, and with such great detail. I will look into it when I get a chance!

**Comment by codeodor** [comment]
I dug into this some today, and it's kind of strange. DisplayCase is reloading the files, in fact. But the changes are not making it into the objects themselves.

Still more to do, but I wanted to update to say `find_definitions.rb` is not the issue, unless it should be doing something more than just loading the files.

**Comment by codeodor** [comment]
I have been trying to find a way to look at the live AST to see what Ruby sees, but I cannot find a gem to do it that also has the side benefit of working.

**Comment by pdobb** [comment]
Thanks, Sammy. I kind of felt the same way... it should be working! Thanks a lot for looking into it. I don't know how I could help with the AST thing... but I see your point about a working one being more of a side benefit than a major selling point. :)

**Comment by codeodor** [comment]
Ok, I figured out the problem.

Since the configuration is explicit, it looks to that array specified in the configuration for the exhibits.

We do not adjust that array when we reload the exhibits, like we do with the non-explicit option. Therefore, it retains a reference to the original class, which is why nothing happens. In reality, a new class is created when it reloads, so we need to modify the array and replace it with the new one.

A kind of hacky way I confirmed this is in `exhibit.rb` the `self.inherited` method, we can do something like:

```ruby
if DisplayCase.respond_to?(:configuration) &&
  DisplayCase.configuration.explicit? &&
  idx = DisplayCase.configuration.exhibits.map(&:name).index(child.name)  
    exhibits = DisplayCase.configuration.exhibits
    exhibits[idx] = child
    DisplayCase.configuration.exhibits = exhibits
end
```

I don't really like that in that place, so I will come up with a better way when I get a chance.

**Comment by codeodor** [comment]
In fact, rather than trying to switch on which source we use for the exhibits, it may be better to just set `@@exhibits` to the explicit config if it exists, and the `inherited` method can then replace it either way, in the original order.

Even the non-explicit option only accidentally works with reloading -- it applies the new version of the class and the old version, so it really doesn't need both, IMO.

**Comment by pdobb** [comment]
Nice! Great to know what's going on. Good explanation.

Another thing I've been thinking about (though it should probably be a different ticket altogether) is inheritance and autoreloading. For example, if I change code in a superclass exhibit then, technically, the child classes should be reloaded too, I think. Anyway, I'm not sure it's not already working out since the explicit autoreloading isn't working. Will concretize that later. But it may end up that the explicit option should define subclasses with e.g.:

    config.exhibits = [
      MyFirstExhibit => [MyFirstExhibitSublcass1, MyFirstExhibitSublcass2],
      MySecondExhibit
    ]

This way we'd know what dependent children to reload if MyFirstExhibit's mtime is updated.

**Comment by codeodor** [comment]
One other thing to note: this only happens (I think) when we get a superclass mismatch error, remove the constant, and then add it back in.

I don't think the explicit option needs to worry about subclasses. Those would not need to be reloaded since they refer to a class that exists, whereas the problem here was that it referred to a class that no longer existed (in our exhibit chain).

However, if you can reproduce it in a test case, then I am happy to look into fixing it.

Wait until you see my test case though, because I might be able to save you some hours in figuring out a way to reproduce it.
