### ISSUE TITLE
Fix for #55 does not work for namespaced exhibits

### ISSUE THREAD

**Issue by codeodor** [objects-on-rails/display-case#57]
@pdobb brought this up in https://github.com/objects-on-rails/display-case/pull/56#issuecomment-157924013. 

Research has found:

The issue with namespacing is that [our code which reloads the class](https://github.com/objects-on-rails/display-case/blob/master/lib/display_case/find_definitions.rb#L25-L28) when there is a superclass mismatch error relies on that error message to know which class needs to be removed and reloaded, but Ruby doesn't provide the fully namespaced class name.

So when we try to `constantize` it, it throws an error that there is no such constant.

The best we can do is search `ObjectSpace` to find the class under its namespace, as a last resort. Even then, I guess we might have issues if you have two classes with the same name under different namespaces.

**Comment by pdobb** [comment]
@codeodor Thanks for getting back to this and for the time spent on the fix! I haven't had 20 minutes to spare since before the holidays still...

Outside of simply searching ObjectSpace (that's a new one for me!), I think the other option would be to allow the user to specify superclass or dependent exhibit hints in the config settings. So if the superclass mismatch happens, we could scan a hash from the config settings, find the class in question, and reload all specified dependent classes at that time.

**Comment by codeodor** [comment]
Thanks!  I feel like at this point, it seems overkill to ask the user to do that, and it won't resolve the ambiguity behind same-class-name-different-namespace...

I'm not opposed to it, but I don't have the time to implement it.
